# StreamVault — Complete Project Blueprint

> This document is a comprehensive prompt that fully describes the StreamVault project. It can be used to recreate, modify, or extend the project from scratch. No local file paths are included — all paths are relative to the project root (`streaming-dashboard/`).

---

## 1. Project Overview

**Name:** StreamVault  
**Type:** Admin Dashboard for a Streaming Platform (IPTV, Movies, Anime)  
**Purpose:** A web-based admin panel to manage live TV channels, movies, anime series, ad networks, and app settings. The dashboard also provides a JSON API for a companion mobile application to consume.  
**Built with:** PHP (vanilla, no framework), MySQL, HTML, CSS (inline + external), JavaScript (vanilla)  
**Architecture:** Custom MVC-like pattern (Controllers, Models, Views, Routes)  
**Font:** Inter (Google Fonts) — weights 300, 400, 500, 600, 700, 800  
**Icon Library:** Font Awesome 6.5.1 (CDN)  
**Auto-Installer:** 4-step graphical installer (requirements check → database setup → admin account → finalize)  
**Authentication:** Session-based login/logout with bcrypt password hashing

---

## 2. Complete File Structure

```
streaming-dashboard/
│
├── .env                                  # Environment config (generated by installer)
├── .htaccess                             # Root — redirects all requests to public/
├── index.php                             # Root entry point — redirects to public/index.php
├── install.sql                           # Database schema — all CREATE TABLE + seed data
│
├── config/
│   └── database.php                      # Parses .env, creates PDO connection
│
├── app/
│   ├── Controllers/
│   │   ├── AuthController.php            # Login/logout/session management
│   │   ├── DashboardController.php       # Dashboard stats (counts + recent items)
│   │   ├── CategoryController.php        # CRUD for categories
│   │   ├── ChannelController.php         # CRUD for channels (with file upload)
│   │   ├── MovieController.php           # CRUD for movies (with poster upload)
│   │   ├── AnimeController.php           # CRUD for anime + episodes (with poster upload)
│   │   ├── AdController.php              # Ad network management (AdMob, AppLovin, StartApp, Unity)
│   │   └── InstallController.php         # 4-step auto-installer logic
│   │
│   └── Models/
│       ├── Category.php                  # categories table — getAll, getById, create, update, delete, count
│       ├── Channel.php                   # channels table — getAll (with JOIN), getById, create, update, delete, count
│       ├── Movie.php                     # movies table — getAll (with JOIN), getById, create, update, delete, count
│       ├── Anime.php                     # anime + anime_episodes tables — full CRUD + episode management
│       └── AdSetting.php                 # ad_settings table — getAll, getByNetwork, save, delete, getActiveAds
│
├── routes/
│   ├── web.php                           # Main dashboard routes — maps ?page=&action= to controllers
│   ├── api.php                           # JSON API endpoints for mobile app
│   └── install.php                       # Installer routes — handles all 4 steps + AJAX
│
├── views/
│   ├── layouts/
│   │   ├── header.php                    # <!DOCTYPE>, <head>, all inline CSS, opens <body> + <div.dashboard-wrapper>
│   │   ├── sidebar.php                   # Sidebar nav + topbar (search, notifications, admin profile, logout)
│   │   └── footer.php                    # Closes wrapper divs, global JS (search filter, sidebar toggle)
│   │
│   ├── auth/
│   │   └── login.php                     # Full standalone login page (own HTML/CSS, glassmorphism design)
│   │
│   ├── dashboard/
│   │   └── index.php                     # Dashboard overview — 4 stat cards + recent channels/movies tables
│   │
│   ├── categories/
│   │   └── form.php                      # Categories list + create/edit form (combined view)
│   │
│   ├── channels/
│   │   ├── index.php                     # Channels list table with actions
│   │   └── form.php                      # Channel create/edit form (name, logo upload, m3u link, category, status)
│   │
│   ├── movies/
│   │   ├── index.php                     # Movies list table with actions
│   │   └── form.php                      # Movie create/edit form (title, description, year, poster, video URL, category)
│   │
│   ├── anime/
│   │   ├── index.php                     # Anime list table with episode count
│   │   └── form.php                      # Anime create/edit form + episode management panel
│   │
│   ├── ads/
│   │   └── settings.php                  # Ad network selector cards + dynamic form fields
│   │
│   ├── settings/
│   │   └── index.php                     # General settings, app update management, danger zone
│   │
│   └── install/
│       ├── layout.php                    # Installer shell — full HTML page with inline CSS + step indicators
│       ├── step1_requirements.php        # PHP version, extensions, writable dirs check
│       ├── step2_database.php            # Database host/name/user/pass form + AJAX test connection
│       ├── step3_admin.php               # Admin email + password form with strength meter
│       └── step4_finish.php              # Summary review + AJAX install execution + success screen
│
├── public/
│   ├── .htaccess                         # Routes non-file requests to index.php + blocks sensitive files
│   ├── index.php                         # Main entry point — installer check → auth gate → router → layout render
│   ├── install.php                       # Installer entry point — loads routes/install.php
│   │
│   ├── assets/
│   │   ├── css/
│   │   │   ├── style.css                 # External CSS (backup/alternate — dashboard uses inline CSS in header.php)
│   │   │   └── header_backup.txt         # Backup of header CSS
│   │   │
│   │   └── js/
│   │       └── ads-manager.js            # AdsManager JS module — dynamic ad network form rendering
│   │
│   └── uploads/                          # User-uploaded files directory
│       ├── channels/                     # Channel logo uploads
│       ├── movies/                       # Movie poster uploads
│       └── anime/                        # Anime poster uploads
```

---

## 3. Color Palette & Design System

### Theme: Premium Sky Blue & White with Glassmorphism

#### Primary Sky Blue Palette
| Token        | Hex       | Usage                                    |
|--------------|-----------|------------------------------------------|
| `--sky-50`   | `#F0F9FF` | Lightest background, hover states        |
| `--sky-100`  | `#E0F2FE` | Light backgrounds, icon backgrounds      |
| `--sky-200`  | `#BAE6FD` | Borders, scrollbar thumb                 |
| `--sky-300`  | `#7DD3FC` | Hover borders, focus ring accents        |
| `--sky-400`  | `#38BDF8` | Primary accent, focus borders, file upload icons |
| `--sky-500`  | `#0EA5E9` | Primary brand color, active states, icons |
| `--sky-600`  | `#0284C7` | Button gradient end, link hover          |
| `--sky-700`  | `#0369A1` | Darkest accent, button hover gradient end |

#### Background & Surface Colors
| Token              | Value                           | Usage                        |
|--------------------|---------------------------------|------------------------------|
| `--bg-body`        | `#F0F4F8`                       | Page background              |
| `--bg-card`        | `rgba(255, 255, 255, 0.72)`     | Glass card background (header.php) |
| `--bg-card-solid`  | `#FFFFFF`                       | Solid card background        |
| `--glass-blur`     | `blur(14px)`                    | Backdrop filter for glass    |
| `--glass-border`   | `rgba(255, 255, 255, 0.6)`      | Glass card border            |

#### Body background includes radial gradients:
```css
background-image:
    radial-gradient(ellipse at 10% 20%, rgba(186, 230, 253, 0.3) 0%, transparent 50%),
    radial-gradient(ellipse at 80% 80%, rgba(186, 230, 253, 0.2) 0%, transparent 50%);
```

#### Text Colors
| Token              | Hex       | Usage                    |
|--------------------|-----------|--------------------------|
| `--text-primary`   | `#1E293B` | Headings, body text      |
| `--text-secondary` | `#475569` | Secondary text, subtitles |
| `--text-muted`     | `#94A3B8` | Placeholders, captions   |

#### Semantic Colors
| Token           | Hex       | Background Token   | Background Hex |
|-----------------|-----------|--------------------| --------------|
| `--success`     | `#10B981` | `--success-bg`     | `#D1FAE5`      |
| `--danger`      | `#EF4444` | `--danger-bg`      | `#FEE2E2`      |
| `--warning`     | `#F59E0B` | `--warning-bg`     | `#FEF3C7`      |
| `--info`        | `#3B82F6` | `--info-bg`        | `#DBEAFE`      |
| Purple stat     | `#7C3AED` | Purple bg           | `#EDE9FE`      |

#### Gradients
| Name                | Value                                                    | Usage             |
|---------------------|----------------------------------------------------------|-------------------|
| `--gradient-side`   | `linear-gradient(160deg, #0EA5E9 0%, #0277BD 50%, #01579B 100%)` | Sidebar background |
| `--gradient-btn`    | `linear-gradient(135deg, #38BDF8, #0284C7)`              | Primary buttons   |
| `--gradient-btn-h`  | `linear-gradient(135deg, #0EA5E9, #0369A1)`              | Button hover      |

#### Border & Focus
| Token            | Value     |
|------------------|-----------|
| `--border`       | `#E2E8F0` |
| `--border-focus` | `#38BDF8` |

#### Sizing Tokens
| Token          | Value   |
|----------------|---------|
| `--sidebar-w`  | `260px` |
| `--topbar-h`   | `64px`  |
| `--radius`     | `14px`  |
| `--radius-sm`  | `10px`  |
| `--radius-xs`  | `6px`   |

#### Shadows
| Token           | Value                                                          |
|-----------------|----------------------------------------------------------------|
| `--shadow-card` | `0 2px 16px rgba(14, 165, 233, 0.06), 0 1px 4px rgba(0,0,0,0.04)` |
| `--shadow-md`   | `0 4px 20px rgba(0, 0, 0, 0.08)`                              |
| `--shadow-lg`   | `0 12px 40px rgba(0, 0, 0, 0.12)`                             |

#### Animations
| Name        | Usage                    | Duration |
|-------------|--------------------------|----------|
| `slideDown` | Alert appearance         | 0.3s     |
| `fadeIn`    | Dynamic field appearance | 0.3s     |
| `float`     | Login background orbs    | 8s       |
| `logoPulse` | Login logo pulse         | 3s       |
| `shakeError`| Login error shake        | 0.4s     |
| `cardSlideUp` | Login card entrance    | 0.6s     |
| `shimmer`   | Installer progress bar   | 2s       |
| `cardIn`    | Installer card entrance  | 0.5s     |
| `popIn`     | Success icon pop         | 0.5s     |
| `spin`      | Loading spinner          | 0.6s-1s  |
| `alertIn`   | Installer alert appear   | 0.35s    |

#### Transition Easing
```css
--ease: cubic-bezier(0.4, 0, 0.2, 1);
```

---

## 4. Database Schema

**Engine:** InnoDB  
**Charset:** utf8mb4  
**Collation:** utf8mb4_unicode_ci

### Tables

#### `admins`
| Column       | Type                                        | Notes                 |
|--------------|---------------------------------------------|-----------------------|
| `id`         | INT AUTO_INCREMENT PRIMARY KEY               |                       |
| `email`      | VARCHAR(200) NOT NULL UNIQUE                 | Login identifier      |
| `password`   | VARCHAR(255) NOT NULL                        | bcrypt hashed         |
| `role`       | ENUM('super_admin','admin','editor')         | Default: 'admin'      |
| `created_at` | DATETIME DEFAULT CURRENT_TIMESTAMP           |                       |

#### `categories`
| Column       | Type                                        | Notes                 |
|--------------|---------------------------------------------|-----------------------|
| `id`         | INT AUTO_INCREMENT PRIMARY KEY               |                       |
| `name`       | VARCHAR(100) NOT NULL                        |                       |
| `type`       | ENUM('general','movie','channel','anime')    | Default: 'general'    |
| `created_at` | DATETIME DEFAULT CURRENT_TIMESTAMP           |                       |

#### `channels`
| Column        | Type                           | Notes                        |
|---------------|--------------------------------|------------------------------|
| `id`          | INT AUTO_INCREMENT PRIMARY KEY  |                              |
| `name`        | VARCHAR(200) NOT NULL           |                              |
| `logo`        | VARCHAR(500) DEFAULT NULL       | Relative path to upload      |
| `m3u_link`    | TEXT NOT NULL                   | Stream URL                   |
| `category_id` | INT DEFAULT NULL                | FK → categories(id) ON DELETE SET NULL |
| `status`      | ENUM('active','inactive')       | Default: 'active'            |
| `created_at`  | DATETIME DEFAULT CURRENT_TIMESTAMP |                           |

#### `movies`
| Column        | Type                           | Notes                        |
|---------------|--------------------------------|------------------------------|
| `id`          | INT AUTO_INCREMENT PRIMARY KEY  |                              |
| `title`       | VARCHAR(300) NOT NULL           |                              |
| `description` | TEXT DEFAULT NULL               |                              |
| `release_year`| YEAR DEFAULT NULL               |                              |
| `poster`      | VARCHAR(500) DEFAULT NULL       | Relative path to upload      |
| `video_url`   | TEXT NOT NULL                   | Stream/download URL          |
| `category_id` | INT DEFAULT NULL                | FK → categories(id) ON DELETE SET NULL |
| `created_at`  | DATETIME DEFAULT CURRENT_TIMESTAMP |                           |

#### `anime`
| Column        | Type                           | Notes                        |
|---------------|--------------------------------|------------------------------|
| `id`          | INT AUTO_INCREMENT PRIMARY KEY  |                              |
| `title`       | VARCHAR(300) NOT NULL           |                              |
| `description` | TEXT DEFAULT NULL               |                              |
| `release_year`| YEAR DEFAULT NULL               |                              |
| `poster`      | VARCHAR(500) DEFAULT NULL       | Relative path to upload      |
| `category_id` | INT DEFAULT NULL                | FK → categories(id) ON DELETE SET NULL |
| `created_at`  | DATETIME DEFAULT CURRENT_TIMESTAMP |                           |

#### `anime_episodes`
| Column          | Type                           | Notes                     |
|-----------------|--------------------------------|---------------------------|
| `id`            | INT AUTO_INCREMENT PRIMARY KEY  |                           |
| `anime_id`      | INT NOT NULL                    | FK → anime(id) ON DELETE CASCADE |
| `episode_number`| INT NOT NULL                    |                           |
| `title`         | VARCHAR(300) DEFAULT NULL       |                           |
| `video_url`     | TEXT NOT NULL                   |                           |
| `created_at`    | DATETIME DEFAULT CURRENT_TIMESTAMP |                        |

#### `ad_settings`
| Column         | Type                           | Notes                    |
|----------------|--------------------------------|--------------------------|
| `id`           | INT AUTO_INCREMENT PRIMARY KEY  |                          |
| `network_name` | VARCHAR(50) NOT NULL UNIQUE     | admob, applovin, startapp, unity |
| `settings_json`| JSON DEFAULT NULL               | Network-specific config  |
| `is_active`    | TINYINT(1) DEFAULT 0            |                          |
| `created_at`   | DATETIME DEFAULT CURRENT_TIMESTAMP |                       |
| `updated_at`   | DATETIME ... ON UPDATE CURRENT_TIMESTAMP |                  |

#### `app_settings`
| Column         | Type                           | Notes                    |
|----------------|--------------------------------|--------------------------|
| `id`           | INT AUTO_INCREMENT PRIMARY KEY  |                          |
| `setting_key`  | VARCHAR(100) NOT NULL UNIQUE    | Key-value store          |
| `setting_value`| TEXT DEFAULT NULL               |                          |

### Default Seed Data

**app_settings:**
- `app_name` = 'StreamVault'
- `app_version` = '1.0.0'
- `app_description` = 'Your ultimate streaming platform'
- `maintenance_mode` = '0'
- `force_update` = '0'
- `show_ads` = '1'
- `enable_channels` = '1'
- `enable_movies` = '1'
- `enable_anime` = '1'

**Additional settings (saved via dashboard):**
- `support_email`, `privacy_url`, `terms_of_service`
- `update_version`, `update_url`, `update_message`, `update_enabled`

**categories (seeds):**
- Action (general), Drama (general), Comedy (general)
- Sports (channel), News (channel)
- Sci-Fi (movie)
- Shonen (anime), Seinen (anime)

---

## 5. .env File Format

Generated by the installer at the end of Step 4:

```
DB_HOST=localhost
DB_NAME=streaming_db
DB_USER=root
DB_PASS=
APP_NAME=StreamVault
APP_URL=
MAINTENANCE_MODE=false
INSTALLED=true
```

The `INSTALLED=true` flag is what `InstallController::isInstalled()` checks. If this flag is missing or false, the app redirects to the installer.

---

## 6. Authentication System

### Flow
1. `public/index.php` starts the session, checks if installed.
2. If `?page=logout` → `AuthController::logout()` destroys session, redirects to login.
3. If `?page=login` → shows the login view. On POST, verifies credentials via `AuthController::login()`.
4. If not logged in (`AuthController::isLoggedIn()` returns false) → redirects to login.
5. If logged in → loads the router, renders the dashboard.

### Session Variables (on successful login)
- `$_SESSION['admin_logged_in']` = `true`
- `$_SESSION['admin_id']` = admin's row ID
- `$_SESSION['admin_email']` = admin's email
- `$_SESSION['admin_role']` = admin's role (super_admin, admin, editor)

### Password Hashing
- Stored with `password_hash($password, PASSWORD_BCRYPT)` during installation
- Verified with `password_verify($password, $hash)` during login

### Logout
- Clears `$_SESSION` array
- Expires the session cookie
- Calls `session_destroy()`
- Redirects to `index.php?page=login`

---

## 7. Routing System

### Dashboard Routes (`public/index.php` → `routes/web.php`)

URL pattern: `index.php?page={page}&action={action}&id={id}`

| Page         | Actions                                         |
|--------------|--------------------------------------------------|
| `dashboard`  | `index` (default)                                |
| `categories` | `index`, `store`, `update`, `delete`, `edit`     |
| `channels`   | `index`, `create`, `edit`, `store`, `update`, `delete` |
| `movies`     | `index`, `create`, `edit`, `store`, `update`, `delete` |
| `anime`      | `index`, `create`, `edit`, `store`, `update`, `delete`, `episodes`, `add_episode`, `delete_episode` |
| `ads`        | `index`, `save`, `delete`                        |
| `settings`   | `index`, `save`                                  |

### API Routes (`routes/api.php`)

URL pattern: `api.php?endpoint={endpoint}`

| Endpoint       | Method | Response                                   |
|----------------|--------|--------------------------------------------|
| `categories`   | GET    | All categories                             |
| `channels`     | GET    | All channels                               |
| `movies`       | GET    | All movies                                 |
| `anime`        | GET    | All anime with episodes                    |
| `ads`          | GET    | Active ad networks with settings           |
| `settings`     | GET    | All app settings key-value pairs           |
| `check-update` | GET    | Update availability, version, URL, message, force flag |

API response format:
```json
{
    "status": "success",
    "data": { ... }
}
```

### Installer Routes (`routes/install.php`)

URL pattern: `install.php?step={1-4}`

| Step | Name          | POST Action                        |
|------|---------------|------------------------------------|
| 1    | Requirements  | Saves to session, redirects step 2 |
| 2    | Database      | Saves DB config to session, AJAX test connection |
| 3    | Admin Account | Saves admin email/pass to session  |
| 4    | Finalize      | AJAX: connects DB, runs SQL, creates admin, writes .env |

---

## 8. Ad Networks Supported

| Network   | Fields                                              |
|-----------|-----------------------------------------------------|
| AdMob     | App ID, Banner ID, Interstitial ID, Rewarded ID, Native ID |
| AppLovin  | SDK Key, Banner Zone ID, Interstitial Zone ID, Rewarded Zone ID |
| StartApp  | App ID, Return Ad (yes/no), Interstitial Type (overlay/video/both) |
| Unity Ads | Game ID, Banner Placement, Interstitial Placement, Rewarded Placement, Test Mode |

---

## 9. Settings Fields

### General Settings (text fields)
- `app_name` — Application name
- `app_version` — Current app version (semantic versioning)
- `app_description` — Brief description
- `support_email` — Contact email
- `privacy_url` — Privacy policy URL
- `terms_of_service` — Terms text

### App Update Fields (text fields)
- `update_version` — Latest available version
- `update_url` — Download/store URL
- `update_message` — Changelog/what's new

### Toggle Fields (boolean, stored as '0'/'1')
- `maintenance_mode` — Puts app in maintenance
- `force_update` — Forces users to update
- `show_ads` — Enables/disables ads
- `enable_channels` — Enables channels section
- `enable_movies` — Enables movies section
- `enable_anime` — Enables anime section
- `update_enabled` — Enables update notifications

---

## 10. File Upload Configuration

| Content  | Upload Directory       | Filename Pattern              |
|----------|------------------------|------------------------------ |
| Channels | `public/uploads/channels/` | `ch_{timestamp}_{uniqid}.{ext}` |
| Movies   | `public/uploads/movies/`   | `mov_{timestamp}_{uniqid}.{ext}` |
| Anime    | `public/uploads/anime/`    | `ani_{timestamp}_{uniqid}.{ext}` |

- Directories are auto-created with `0755` permissions
- Files are stored with relative paths (e.g., `uploads/channels/ch_1234_abc.jpg`)

---

## 11. UI Component Summary

### Dashboard Layout
- **Sidebar** (260px, fixed left) — gradient sky blue, brand logo, nav links, footer
- **Topbar** (64px, sticky top) — search input, notification bell, fullscreen toggle, admin profile, logout button
- **Page Content** — padded area with breadcrumbs and dynamic content

### Dashboard Page
- 4 stat cards in a grid (Categories, Channels, Movies, Anime) with icons and trend badges
- 2-column recent content grid (Recent Channels table, Recent Movies table)

### Login Page (standalone)
- Centered glassmorphism card with animated background orbs
- Sky-blue gradient brand header with pulsing logo
- Email + password fields with icons
- Password visibility toggle
- Error display with shake animation
- Responsive design

### Installer (standalone)
- Centered card with animated background bubbles
- 4-step progress bar with shimmer effect
- Step circles (numbered, active glow, done checkmarks)
- Step-specific views with consistent form styling
- AJAX database test + AJAX installation with spinner
- Success screen with pop-in checkmark animation

---

## 12. External Dependencies (CDN)

| Resource           | URL                                                                           |
|--------------------|-------------------------------------------------------------------------------|
| Google Fonts (Inter) | `https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800` |
| Font Awesome 6.5.1  | `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css`  |

No other external libraries, frameworks, or package managers are used. The project is pure PHP + vanilla HTML/CSS/JS.

---

## 13. Server Requirements

- PHP >= 7.4
- Extensions: `pdo`, `pdo_mysql`, `mbstring`, `json`
- MySQL database
- Apache with `mod_rewrite` (for .htaccess routing)
- Writable `.env` file location
- Writable `public/uploads/` directory

---

## 14. Security Features

- `.htaccess` blocks access to `.env`, `.sql`, `.md`, `.log` files
- Passwords hashed with bcrypt (`PASSWORD_BCRYPT`)
- Prepared statements (PDO) for all database queries — prevents SQL injection
- `htmlspecialchars()` used on all output — prevents XSS
- Session-based authentication with cookie expiry on logout
- Installer auto-blocks after `INSTALLED=true` is set in `.env`
- Login form returns generic "Invalid email or password" for both wrong email and wrong password

---

## 15. CSS Architecture

The dashboard uses **two CSS systems** working together:

1. **Inline CSS in `views/layouts/header.php`** (lines 14–1358) — This is the **primary, active stylesheet** containing all dashboard styles. It uses glassmorphism effects (`backdrop-filter: blur()`, semi-transparent backgrounds).

2. **External CSS in `public/assets/css/style.css`** — This is a **backup/alternate version** of the same styles without glassmorphism. It uses solid white backgrounds instead.

3. **Login page CSS** — `views/auth/login.php` has its own complete inline stylesheet (standalone page, not wrapped in the dashboard layout).

4. **Installer CSS** — `views/install/layout.php` has its own complete inline stylesheet (standalone page with its own design system).

---

*End of Project Blueprint*
