[php]
documentRoot = "public"

[php.ini]
display_errors = "Off"
expose_php = "Off"
upload_max_filesize = "32M"
post_max_size = "32M"
max_execution_time = "60"

[caddy]
config = """
{
    frankenphp
}

:80 {
    root * /app/public

    @notFile {
        not file
        not path /
    }
    rewrite @notFile /index.php

    php_server {
        index index.php
    }

    file_server
}
"""
